// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System.Collections.Generic;

	public static class Archetypes
	{
		public const int Player__char_32___char_40_Networked__char_41__a32b95e2821e79946ba725f1067bb08cIndex = 0;

		public static Dictionary<string, int> IndexForName = new Dictionary<string, int>() {
			{ "Player__char_32___char_40_Networked__char_41__a32b95e2821e79946ba725f1067bb08c", 0 },

		};
	}
}
